helper_vm_ip: 10.46.27.151
helper_name: bastion2
bootstrap_ignition_url: "http://{{helper_vm_ip}}:8080/ocp4/bootstrap.ign"
ansible_os_family: 'linux'
config:
#   provider: none
  provider: vsphere
  base_domain: ocp.lan
  cluster_name: lab
  fips: false
  #networkType: OVNKubernetes
  # Network Policy is enabled by default. To use Multitenant or Subnet, change isolationMode
  #isolationMode: Multitenant
  installer_ssh_key: "{{ lookup('file', '~/.ssh/ocp4.pub') }}"
  pull_secret: "{{ lookup('file', 'pullsecret.txt') }}"
vcenter:
  ip: 10.46.27.86
  datastore: datastore2
  network: OCP
  service_account_username: administrator@vsphere.local
  service_account_password: cajamar+_A2
  admin_username: administrator@vsphere.local
  admin_password: cajamar+_A2
  datacenter: Datacenter
  folder_absolute_path:
  vm_power_state: poweredon
  template_name: rhcos-vmware-template
download:
  clients_url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest
  dependencies_url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/latest/latest
  govc: https://github.com/vmware/govmomi/releases/download/v0.27.4
bootstrap_vms:
# # For static ips  VMware will auto-generate your MAC addresses (delete macaddr)
#   - { name: "bootstrap", macaddr: "00:50:56:00:00:00", ipaddr: "192.168.22.200", cpu: 4, ram: 16384}
# master_vms:
#   - { name: "control-plane-0", macaddr: "00:50:56:a8:aa:a2", ipaddr: "192.168.22.201", cpu: 4, ram: 16384}
#   - { name: "control-plane-1", macaddr: "00:50:56:a8:aa:a3", ipaddr: "192.168.22.202", cpu: 4, ram: 16384}
#   - { name: "control-plane-2", macaddr: "00:50:56:a8:aa:a4", ipaddr: "192.168.22.203", cpu: 4, ram: 16384}
# worker_vms:
#   - { name: "worker-0", macaddr: "00:50:56:a8:aa:a5", ipaddr: "192.168.22.211", cpu: 4, ram: 16384}
#   - { name: "worker-1", macaddr: "00:50:56:a8:aa:a6", ipaddr: "192.168.22.212", cpu: 4, ram: 16384}
#   - { name: "worker-2", macaddr: "00:50:56:a8:aa:a7", ipaddr: "192.168.22.213", cpu: 4, ram: 16384}
  - { name: "bootstrap", ipaddr: "192.168.22.200", cpu: 4, ram: 16384}
master_vms:
  - { name: "control-plane-0", ipaddr: "192.168.22.201", cpu: 4, ram: 16384}
  - { name: "control-plane-1",  ipaddr: "192.168.22.202", cpu: 4, ram: 16384}
  - { name: "control-plane-2", ipaddr: "192.168.22.203", cpu: 4, ram: 16384}
worker_vms:
  - { name: "worker-0", ipaddr: "192.168.22.211", cpu: 4, ram: 16384}
  - { name: "worker-1",  ipaddr: "192.168.22.212", cpu: 4, ram: 16384}
  - { name: "worker-2",  ipaddr: "192.168.22.213", cpu: 4, ram: 16384}
static_ip:
  gateway: 192.168.22.1
  netmask: 255.255.255.0
  dns: 192.168.22.1
  network_interface_name: ens192
# For network_modifications: Network CIDRs default to sensible ranges.  
network_modifications:
  enabled: false
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  serviceNetwork:
  - cidr: 172.30.0.0/16
  machineNetwork:
  - cidr: 192.168.29.0/24
# If proxy.enabled is set to False anything defined under proxy and the proxy setup is ignored  
proxy:
  enabled: false
  http_proxy: http://{{helper_name}}.{{config.cluster_name}}.{{config.base_domain}}:3129
  https_proxy: http://{{helper_name}}.{{config.cluster_name}}.{{config.base_domain}}:3129
  no_proxy: lab.ocp.lan
  cert_content: |
    -----BEGIN CERTIFICATE-----
        <certficate content>
    -----END CERTIFICATE-----
# When doing the restricted network install and following instructions from restricted.md, furnish details related to the registry with a section like below. If registry.enabled is set to False anything defined under registry and the registry setup is ignored    
registry:
  enabled: true
  product_repo: openshift-release-dev
  product_release_name: ocp-release
  product_release_version: 4.9.0-x86_64
  username: ansible
  password: ansible
  email: user@awesome.org
  cert_content:
  host: registry.lab.ocp.lan
  port: 5000
  repo: ocp4/openshift4
# If you wish to enable custom NTP servers on your nodes, set ntp.custom to True and define ntp.ntp_server_list to fit your requirements.  
ntp:
  custom: false
  ntp_server_list:
    - 0.rhel.pool.ntp.org
    - 1.rhel.pool.ntp.org
